### ISSUE TITLE
How long before nodejs 6 deprecated?

### ISSUE THREAD

**Issue by rcwwilliams** [sclorg/s2i-nodejs-container#209]
Hi

We currently have an application using nodejs 6 and it requires a bit of work to be updated to a later version.  When would you expect 6 to be deprecated, please?

Thanks

Robin

**Comment by pkubatrh** [comment]
Hi @rcwwilliams 

an SCL image gets deprecated when the underlying SCL rpms get deprecated. You can find information about the lifecycle for each collection in the [customer portal](https://access.redhat.com/support/policy/updates/rhscl).

Looking at the list right now, nodejs6 has been deprecated since last month.
